version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile  # Cambiado a tu nombre de archivo actual
      target: development
    container_name: real-estate-analyzer-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge