version: '3.8'

services:
  test:
    build: 
      context: .
      target: testing
    image: xwataryx/real-estate-analyzer:test
    container_name: real-estate-analyzer-test
    environment:
      - NODE_ENV=test
    networks:
      - test-network

networks:
  test-network:
    driver: bridge