# docker-compose.test.yml
version: '3.8'

services:
  test:
    build: 
      context: .
      target: testing  # Usa el stage de testing
    container_name: real-estate-analyzer-test
    environment:
      - NODE_ENV=test
    networks:
      - test-network

networks:
  test-network:
    driver: bridge