version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: real-estate-analyzer
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/app/.env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge