# Stage 1: Dependencies
FROM node:18-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm install

# Stage 2: Testing
FROM deps AS testing
COPY . .
RUN npm run test

# Stage 3: Builder
FROM deps AS builder
COPY . .
RUN npm run build

# Stage 4: Development
FROM deps AS development
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start:dev"]

# Stage 5: Production
FROM node:18-alpine AS production
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production
COPY --from=builder /app/dist ./dist
# COPY --from=builder /app/.env ./.env
EXPOSE 3000
CMD ["npm", "run", "start:prod"]
